"""Add pdf_data column to Note model

Revision ID: 390b294eba51
Revises: 
Create Date: 2024-04-13 09:16:55.956040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390b294eba51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('thumbnail_filename')
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('thumbnail_data')
        batch_op.drop_column('pdf_data')

    # ### end Alembic commands ###
